packages:
- 'hastory'
- 'hastory-test-utils'
extra-deps:
- validity-0.4.0.2
- validity-path-0.2.0.2
- validity-time-0.1.0.0
- validity-text-0.2.0.0
- genvalidity-0.4.0.0
- genvalidity-path-0.2.0.0
- genvalidity-text-0.4.0.0
- genvalidity-time-0.1.0.0
- genvalidity-property-0.1.0.0
- genvalidity-hspec-0.5.0.0
- genvalidity-hspec-aeson-0.1.0.1
resolver: lts-8.15
