resolver: lts-15.15
packages:
- hastory-api
- hastory-cli
- hastory-data
- hastory-data-gen
- hastory-server
extra-deps:
- base64-0.4.2
- ghc-byteorder-4.11.0.0.10
- password-2.0.1.1
- password-instances-2.0.0.1
- servant-auth-client-0.4.0.0
- yamlparse-applicative-0.1.0.1
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
- github: NorfairKing/validity
  commit: c38fc635f98580548f82314504e9f8742519f94d
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e3a2247046d4de66b9b193a6ab3ff040fa3da86d.tar.gz" ]
  add-gc-roots: true
  packages:
  - haskellPackages.autoexporter
  - killall
  - zlib
