resolver: lts-14.23
packages:
- hastory-cli
- hastory-data
- hastory-cli-data
- hastory-data-gen
- hastory-server-data
- hastory-path
- hastory-server
extra-deps:
- base64-0.4.2
- ghc-byteorder-4.11.0.0.10
- password-2.0.1.1
- password-instances-2.0.0.1
- github: NorfairKing/validity
  commit: 04ef274e8be3595f5846645f5922791292653e03
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e6b93257b0ba070bd12810eeacbe281396c24316.tar.gz" ]
  add-gc-roots: true
  packages:
  - zlib
