name: hastory-data-gen
version: '0.0.0.0'
category: Command Line
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/hastory

dependencies:
- hastory-data
- path
- path-io

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Data.Hastory.Gen
  dependencies:
  - QuickCheck
  - base >=4.9 && <=5
  - genvalidity
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-path
  - genvalidity-text
  - genvalidity-time
  - hspec
  - validity
  - validity-path
  - validity-text

tests:
  hastory-data-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - hastory-data-gen
    - genvalidity
    - genvalidity-hspec
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - genvalidity-hspec-aeson
    - hspec
    - validity
    - validity-path
    - validity-text
    - QuickCheck
    - safe
    - text

benchmarks:
  hastory-data-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -Wall
    dependencies:
    - base
    - hastory-data-gen
    - exceptions
    - genvalidity
    - criterion
    - QuickCheck
    - mtl
