ghc-options: ["-optP-Wno-nonportable-include-path"]
name: hastory-cli
version: '0.0.0.0'
category: Command Line
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/hastory
dependencies:
- base >=4.9 && <=5
- hastory-cli-data

library:
  source-dirs: src/
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  dependencies:
  - aeson
  - aeson-pretty
  - bytestring
  - deepseq
  - envparse
  - exceptions
  - extra
  - hashable
  - hashable-time
  - hastory-data
  - hostname
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent-sqlite
  - resourcet
  - safe
  - servant-client
  - servant-client-core
  - text
  - time
  - unix
  - unliftio-core
  - unordered-containers
  - validity
  - validity-path
  - validity-text
  - validity-time
  - yamlparse-applicative

executables:
  hastory:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hastory-cli

tests:
  hastory-cli-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - QuickCheck
    - aeson
    - bytestring
    - envparse
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - hastory-cli
    - hastory-data
    - hastory-data-gen
    - hastory-server
    - hspec
    - mtl
    - optparse-applicative
    - path
    - path-io
    - safe
    - servant-client
    - servant-client-core
    - text
    - validity
    - validity-path
    - validity-text
    - yaml

benchmarks:
  hastory-cli-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    - -Wall
    dependencies:
    - base
    - QuickCheck
    - criterion
    - exceptions
    - genvalidity
    - hastory-cli
    - hastory-data
    - hastory-data-gen
    - mtl
    - path
    - path-io
    - silently
    - unliftio
