name:                hastory-digest
version:             0.0.0.0
homepage:            https://github.com/NorfairKing/hastory
license:             AllRightsReserved
author:              Tom Sydney Kerckhove
maintainer:          syd.kerckhove@gmail.com
copyright:           2020 Tom Sydney Kerckhove
category:            Command Line

dependencies:
  - base >=4.9 && <=5

library:
  source-dirs: src/
  dependencies:
    - bytestring
    - cryptonite
    - memory
    - persistent
  exposed-modules:
    - Data.Hastory.Types.Digest
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -fhide-source-paths
