name:                hastory-data
version:             0.0.0.0
homepage:            https://github.com/NorfairKing/hastory
license:             AllRightsReserved
author:              Tom Sydney Kerckhove
maintainer:          syd.kerckhove@gmail.com
copyright:           2020 Tom Sydney Kerckhove
category:            Command Line

dependencies:
  - base >=4.9 && <=5

library:
  source-dirs: src/
  dependencies:
    - aeson
    - base64
    - bytestring
    - cryptonite
    - deepseq
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - hostname
    - memory
    - password
    - password-instances
    - path
    - persistent
    - persistent-sqlite
    - persistent-template
    - servant-auth-server
    - text
    - time
    - validity
    - validity-text
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -fhide-source-paths
