name: hastory-data
version: '0.0.0.0'
category: Command Line
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/hastory

dependencies:
- base >=4.9 && <=5


library:
  source-dirs: src/
  default-extensions:
  - NoImplicitPrelude
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wimplicit-prelude
  - -Wredundant-constraints

  exposed-modules:
  - Data.Hastory
  - Data.Hastory.Gather
  - Data.Hastory.Types
  - Data.Hastory.Utils

  dependencies:
  - deepseq
  - exceptions
  - hashable
  - hashable-time
  - hostname
  - mtl
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe
  - text
  - time
  - unix
  - unordered-containers
  - validity
  - validity-path
  - validity-text
  - validity-time
