name: hastory-server
version: '0.0.0.0'
category: Command Line
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/hastory

dependencies:
- base >=4.9 && <=5
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

library:
  source-dirs: src/
  exposed-modules:
  - Data.Hastory.Server
  - Data.Hastory.Server.TestUtils

  dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - conduit
  - deepseq
  - exceptions
  - hashable
  - hashable-time
  - hastory-data
  - hostname
  - hspec
  - http-client
  - http-types
  - monad-logger
  - mtl
  - optparse-applicative
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - random
  - resource-pool
  - safe
  - servant
  - servant-client
  - servant-server
  - text
  - time
  - unix
  - unordered-containers
  - validity
  - validity-path
  - validity-text
  - wai
  - warp

executables:
  hastory-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - monad-logger
      - hastory-server

tests:
  hastory-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hastory-data
    - hastory-server
    - hspec
    - http-types
    - path
    - persistent-sqlite
    - servant-client
    - time
