name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: free disk space
      run: |
        sudo rm -rf /opt
    - uses: cachix/cachix-action@releases/v8
      with:
        name: hastory
        extraPullNames: validity
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix
