name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@releases/v3
      with:
        name: validity
        skipNixBuild: true
    - uses: cachix/cachix-action@releases/v3
      with:
        name: hastory
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
